data_dir_Max_processed = "/local/home/lhauptmann/thesis/data/MaxDataset_0to7_100Hz"
data_dir_Apple_processed = "/local/home/lhauptmann/thesis/data/AppleDataset_0to6_50Hz"
data_dir_M2Sleep_processed = "/local/home/lhauptmann/thesis/data/M2Sleep_processed_50Hz"
data_dir_Capture24_processed = "/local/home/lhauptmann/thesis/data/capture24_processed_100Hz_sleep"
plot_dir = "/local/home/lhauptmann/thesis/CL-HAR/plots"
results_dir = "/local/home/lhauptmann/thesis/CL-HAR/results"